name: 'Create test run for PR'
on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

jobs:
  createTestRun:
    runs-on: ubuntu-latest
    steps:
      - name: Create testrun
        uses: luzlab/testrail-createTestRun-action@main
        with:
          testrail_token: ${{ secrets.TESTRAIL_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          testrail_user: 0cd6ff85.thermofisher.onmicrosoft.com@amer.teams.ms
          testrail_suite: 25
          testrail_project: 7
